title: Jill Metcalfe
description: Developer & Problem Solver
author: Jill Metcalfe

# Al-folio style name components
first_name: Jill
middle_name: 
last_name: Metcalfe

baseurl: ""
url: "https://jillmetcalfe.github.io"

# Footer configuration
footer_text: >
  Powered by <a href="https://jekyllrb.com/" target="_blank" rel="noopener noreferrer">Jekyll</a> with a custom theme.
  Hosted by <a href="https://pages.github.com/" target="_blank" rel="noopener noreferrer">GitHub Pages</a>.
footer_fixed: false
last_updated: true

# Newsletter (disabled for now)
newsletter:
  enabled: false

# Build settings
markdown: kramdown
theme: minima

# Social links (LinkedIn only)
linkedin_username: jillmetcalfe

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  books:
    output: true
    permalink: /:collection/:name/

# Navigation pages (order matters)
header_pages:
  - about.md
  - projects.md
  - bookshelf.md
  - now.md

# Plugins
plugins:
  - jekyll-feed

# Exclude email from footer (minima automatically includes it if present)
# By not including email field, we keep contact to LinkedIn only
