title: Jill Metcalfe
description: Developer & Problem Solver
author: Jill Metcalfe

baseurl: ""
url: "https://jillmetcalfe.github.io"

# Build settings
markdown: kramdown
theme: minima

# Social links (LinkedIn only)
linkedin_username: jillmetcalfe

# Collections
collections:
  projects:
    output: true
    permalink: /:collection/:name/
  books:
    output: true
    permalink: /:collection/:name/

# Navigation pages (order matters)
header_pages:
  - about.md
  - projects.md
  - bookshelf.md
  - now.md

# Plugins
plugins:
  - jekyll-feed

# Exclude email from footer (minima automatically includes it if present)
# By not including email field, we keep contact to LinkedIn only
