name: Deploy Hugo Site

on:
  push:
    branches:
      - main  # Runs whenever you push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.143.1'
          extended: true

      - name: Build site
        run: hugo --minify

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          ssh_key: ${{ secrets.ACTIONS_DEPLOY_SSH_KEY }}
          publish_dir: ./public


